-- Usuarios y permisos ---------------------------------------------------------

CREATE TABLE usuario (
    id_usuario          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario      varchar(50)  NOT NULL UNIQUE,
    nombre              varchar(60)  NOT NULL,
    apellido            varchar(60)  NOT NULL,
    correo              varchar(120),
    contrasena          varchar(255) NOT NULL,
    codigo_autorizacion varchar(64)  UNIQUE,
    estado              boolean      NOT NULL DEFAULT true
);

CREATE TABLE rol (
    id_rol      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol         varchar(50)  NOT NULL UNIQUE,
    descripcion varchar(250)
);

CREATE TABLE usuario_rol (
    id_usuario int NOT NULL REFERENCES usuario ON DELETE CASCADE,
    id_rol     int NOT NULL REFERENCES rol ON DELETE CASCADE,
    PRIMARY KEY (id_usuario, id_rol)
);

CREATE TABLE permiso (
    id_permiso  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modulo      varchar(40)  NOT NULL UNIQUE,
    descripcion varchar(250),
    CONSTRAINT permiso_formato_modulo_accion CHECK (modulo ~ '^[a-z_]+\.[a-z_]+$')
);

CREATE TABLE rol_permiso (
    id_rol     int NOT NULL REFERENCES rol ON DELETE CASCADE,
    id_permiso int NOT NULL REFERENCES permiso ON DELETE CASCADE,
    PRIMARY KEY (id_rol, id_permiso)
);

-- Catálogo y stock -------------------------------------------------------------

-- El límite de dos niveles de la jerarquía lo valida la aplicación (ADR negocio 0002).
CREATE TABLE categoria (
    id_categoria int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       varchar(100) NOT NULL UNIQUE,
    descripcion  varchar(500),
    id_familia   int REFERENCES categoria,
    estado       boolean NOT NULL DEFAULT true,
    CONSTRAINT categoria_no_es_su_propia_familia CHECK (id_familia <> id_categoria)
);

CREATE TABLE ubicacion (
    id_ubicacion int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector       varchar(20) NOT NULL,
    estante      varchar(20) NOT NULL,
    UNIQUE (sector, estante)
);

CREATE TABLE producto (
    id_producto     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          varchar(150)  NOT NULL,
    descripcion     varchar(1000),
    id_categoria    int           NOT NULL REFERENCES categoria,
    id_ubicacion    int           REFERENCES ubicacion,
    costo_unitario  numeric(12,2) NOT NULL CHECK (costo_unitario >= 0),
    precio_unitario numeric(12,2) NOT NULL CHECK (precio_unitario >= 0), -- neto, sin IVA
    stock_minimo    int           NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
    stock_actual    int           NOT NULL DEFAULT 0,
    imagen          varchar(255),
    estado          boolean       NOT NULL DEFAULT true,
    motivo_baja     varchar(500),
    observacion     varchar(500)
);

CREATE TABLE codigo_barra (
    id_codigo_barra int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          varchar(50) NOT NULL UNIQUE,
    id_producto     int         NOT NULL REFERENCES producto
);

CREATE TABLE proveedor (
    id_proveedor int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razon_social varchar(150) NOT NULL,
    cuit         char(11)     UNIQUE,
    telefono     varchar(30),
    correo       varchar(120),
    direccion    varchar(250)
);

-- Clientes y ventas ------------------------------------------------------------

CREATE TABLE tipo_persona (
    id_tipo_persona int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          varchar(20) NOT NULL UNIQUE
);

-- codigo_arca: código del tipo en las tablas de ARCA, para la emisión fiscal futura (ADR negocio 0010).
CREATE TABLE tipo_documento (
    id_tipo_documento int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            varchar(20) NOT NULL UNIQUE,
    codigo_arca       smallint    NOT NULL UNIQUE
);

CREATE TABLE condicion_iva (
    id_condicion_iva int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           varchar(60) NOT NULL UNIQUE,
    codigo_arca      smallint    NOT NULL UNIQUE
);

CREATE TABLE cliente (
    id_cliente             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_persona        int          NOT NULL REFERENCES tipo_persona,
    nombre_razon_social    varchar(180) NOT NULL,
    id_tipo_documento      int          NOT NULL REFERENCES tipo_documento,
    nro_documento          varchar(20)  NOT NULL,
    id_condicion_iva       int          NOT NULL REFERENCES condicion_iva,
    domicilio_facturacion  varchar(250),
    telefono               varchar(30),
    correo                 varchar(120),
    es_sistema             boolean      NOT NULL DEFAULT false,
    estado                 boolean      NOT NULL DEFAULT true,
    motivo_baja            varchar(500),
    observacion            varchar(500)
);

-- Solo puede existir un cliente del sistema: Consumidor Final (ADR negocio 0004).
CREATE UNIQUE INDEX cliente_unico_de_sistema ON cliente (es_sistema) WHERE es_sistema;

-- Sin columna saldo: se calcula a partir de los movimientos (ADR negocio 0005).
CREATE TABLE cuenta_corriente (
    id_cuenta_corriente int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente          int           NOT NULL UNIQUE REFERENCES cliente,
    limite_credito      numeric(12,2) NOT NULL CHECK (limite_credito >= 0)
);

CREATE TABLE venta (
    id_venta             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente           int           NOT NULL REFERENCES cliente,
    id_vendedor          int           NOT NULL REFERENCES usuario,
    condicion_pago       varchar(20)   NOT NULL CHECK (condicion_pago IN ('CONTADO', 'CUENTA_CORRIENTE')),
    medio_pago           varchar(20)   CHECK (medio_pago IN ('EFECTIVO', 'TRANSFERENCIA', 'TARJETA', 'OTRO')),
    estado               varchar(25)   NOT NULL CHECK (estado IN ('PENDIENTE_AUTORIZACION', 'CONFIRMADA', 'RECHAZADA')),
    porcentaje_descuento numeric(5,2)  NOT NULL DEFAULT 0 CHECK (porcentaje_descuento BETWEEN 0 AND 100),
    total                numeric(14,2) NOT NULL DEFAULT 0,
    observaciones        varchar(500),
    fecha_hora           timestamptz   NOT NULL DEFAULT now(),
    fecha_confirmacion   timestamptz
);

CREATE TABLE item_venta (
    id_venta        int           NOT NULL REFERENCES venta,
    id_producto     int           NOT NULL REFERENCES producto,
    cantidad        int           NOT NULL CHECK (cantidad > 0),
    precio_unitario numeric(12,2) NOT NULL, -- neto, congelado al vender
    costo_unitario  numeric(12,2) NOT NULL, -- congelado al vender
    alicuota_iva    numeric(5,2)  NOT NULL, -- congelada al vender
    subtotal        numeric(14,2) NOT NULL,
    PRIMARY KEY (id_venta, id_producto)
);

-- Comprobantes -------------------------------------------------------------------

CREATE TABLE comprobante (
    id_comprobante   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente       int           NOT NULL REFERENCES cliente,
    id_usuario       int           NOT NULL REFERENCES usuario,
    tipo_comprobante varchar(20)   NOT NULL,
    modo_emision     varchar(10)   NOT NULL DEFAULT 'INTERNO' CHECK (modo_emision IN ('INTERNO', 'FISCAL')),
    punto_venta      int           NOT NULL DEFAULT 1,
    numero           bigint        NOT NULL,
    fecha_emision    timestamptz   NOT NULL DEFAULT now(),
    importe_total    numeric(14,2) NOT NULL,
    cae              varchar(20),  -- uso futuro fiscal (ADR negocio 0010)
    cae_vencimiento  date,         -- uso futuro fiscal
    UNIQUE (tipo_comprobante, modo_emision, punto_venta, numero)
);

CREATE TABLE factura (
    id_comprobante int PRIMARY KEY REFERENCES comprobante,
    id_venta       int NOT NULL UNIQUE REFERENCES venta
);

CREATE TABLE nota (
    id_comprobante    int PRIMARY KEY REFERENCES comprobante,
    id_factura_origen int          NOT NULL REFERENCES factura,
    tipo_nota         varchar(10)  NOT NULL CHECK (tipo_nota IN ('CREDITO', 'DEBITO')),
    motivo_tipo       varchar(20)  NOT NULL CHECK (motivo_tipo IN ('DEVOLUCION', 'MORA')),
    motivo            varchar(500) NOT NULL,
    medio_pago        varchar(20)  CHECK (medio_pago IN ('EFECTIVO', 'TRANSFERENCIA', 'TARJETA', 'OTRO'))
);

CREATE TABLE item_nota (
    id_comprobante  int           NOT NULL REFERENCES nota,
    id_producto     int           NOT NULL REFERENCES producto,
    cantidad        int           NOT NULL CHECK (cantidad > 0),
    precio_unitario numeric(12,2) NOT NULL, -- de la venta original
    alicuota_iva    numeric(5,2)  NOT NULL, -- de la venta original
    reingresa_stock boolean       NOT NULL,
    PRIMARY KEY (id_comprobante, id_producto)
);

CREATE TABLE recibo (
    id_comprobante int PRIMARY KEY REFERENCES comprobante,
    medio_pago     varchar(20)  NOT NULL CHECK (medio_pago IN ('EFECTIVO', 'TRANSFERENCIA', 'TARJETA', 'OTRO')),
    observacion    varchar(500)
);

CREATE TABLE autorizacion (
    id_autorizacion  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo             varchar(30)  NOT NULL CHECK (tipo IN ('CREDITO_EXCEDIDO', 'PRODUCTO_INACTIVO', 'CLIENTE_INACTIVO', 'DESCUENTO', 'DEVOLUCION')),
    estado           varchar(15)  NOT NULL CHECK (estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA')),
    id_venta         int          REFERENCES venta,
    id_comprobante   int          REFERENCES comprobante, -- nota de devolución
    id_solicitante   int          NOT NULL REFERENCES usuario,
    id_autorizador   int          REFERENCES usuario,     -- NULL mientras está PENDIENTE
    datos            jsonb,
    motivo           varchar(500),
    fecha_solicitud  timestamptz  NOT NULL DEFAULT now(),
    fecha_resolucion timestamptz
);

-- Movimientos ----------------------------------------------------------------------

CREATE TABLE movimiento_stock (
    id_movimiento_stock int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto         int          NOT NULL REFERENCES producto,
    id_usuario          int          NOT NULL REFERENCES usuario,
    id_proveedor        int          REFERENCES proveedor,
    id_venta            int          REFERENCES venta, -- tipo VENTA
    id_nota             int          REFERENCES nota,  -- tipo DEVOLUCION
    tipo                varchar(20)  NOT NULL CHECK (tipo IN ('INGRESO', 'AJUSTE', 'VENTA', 'DEVOLUCION')),
    cantidad            int          NOT NULL,
    motivo              varchar(500),
    fecha_carga         timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE movimiento_cuenta_corriente (
    id_movimiento_cc    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta_corriente int           NOT NULL REFERENCES cuenta_corriente,
    id_comprobante      int           UNIQUE REFERENCES comprobante,
    id_usuario          int           NOT NULL REFERENCES usuario,
    tipo_movimiento     varchar(20)   NOT NULL CHECK (tipo_movimiento IN ('SALDO_INICIAL', 'FACTURA', 'NOTA_CREDITO', 'NOTA_DEBITO', 'RECIBO', 'AJUSTE')),
    sentido             varchar(7)    NOT NULL CHECK (sentido IN ('DEBITO', 'CREDITO')),
    importe             numeric(14,2) NOT NULL CHECK (importe > 0),
    fecha_hora          timestamptz   NOT NULL DEFAULT now(),
    fecha_vencimiento   date,         -- solo débitos
    observacion         varchar(500)
);

CREATE TABLE imputacion (
    id_imputacion         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_movimiento_credito int           NOT NULL REFERENCES movimiento_cuenta_corriente,
    id_movimiento_debito  int           NOT NULL REFERENCES movimiento_cuenta_corriente,
    importe_imputado      numeric(14,2) NOT NULL CHECK (importe_imputado > 0),
    fecha_imputacion      timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT imputacion_entre_movimientos_distintos CHECK (id_movimiento_credito <> id_movimiento_debito)
);

-- Auditoría y configuración ------------------------------------------------------------

CREATE TABLE auditoria (
    id_auditoria        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario          int          NOT NULL REFERENCES usuario,
    accion              varchar(40)  NOT NULL,
    entidad             varchar(50)  NOT NULL,
    id_entidad          varchar(50)  NOT NULL,
    fecha_hora          timestamptz  NOT NULL DEFAULT now(),
    valores_anteriores  jsonb,
    valores_posteriores jsonb,
    motivo              varchar(500)
);

CREATE TABLE configuracion (
    id_configuracion        int          PRIMARY KEY DEFAULT 1 CHECK (id_configuracion = 1),
    modo_comprobante        varchar(10)  NOT NULL DEFAULT 'INTERNO' CHECK (modo_comprobante IN ('INTERNO', 'FISCAL')),
    alicuota_iva            numeric(5,2) NOT NULL DEFAULT 21,
    descuento_max_vendedor  numeric(5,2) NOT NULL DEFAULT 10,
    dias_vencimiento        int          NOT NULL DEFAULT 30,
    tasa_mora               numeric(7,4), -- diaria
    tipo_regla_precio       varchar(10)  NOT NULL DEFAULT 'RECARGO',
    porcentaje_regla_precio numeric(5,2) NOT NULL DEFAULT 0,
    tamano_max_archivo      int,
    cantidad_max_archivo    int,
    punto_venta_fiscal      int,          -- uso futuro fiscal
    ambiente_fiscal         varchar(20)   -- uso futuro fiscal
);
